### ISSUE TITLE
[CS] Killfeed writes incorrect information when player kills player

### ISSUE THREAD

**Issue by Nord1cWarr1or** [JulianR0/monstermod-redo#11]
Killfeed by monstermod writes incorrect information. If player kills a player, mod says: `* <nick> died mysteriously.`

**Comment by JulianR0** [comment]
Apologies for the long delay, it should be okay now.

**Comment by Nord1cWarr1or** [comment]
> Apologies for the long delay, it should be okay now.

No problem :)
Yes, it's OK. 

Is it possible (for example, make a cvar) to disable this line when PvP? Because in the same Counter-Strike there is a standard KillFeed

**Comment by Nord1cWarr1or** [comment]
OK thanks for the answer
