### ISSUE TITLE
 Let's make the world more convenient, save the limits.

### ISSUE THREAD

**Issue by QuakerLife** [JulianR0/monstermod-redo#2]
Why not make precache and spawn monsters, from maps. (mp_allowmonster 1)

**Comment by JulianR0** [comment]
Using the already existant monsters from a mod's does not magically "lower" the precache count. The mod's monsters and this plugin's monsters count towards the same counter, they are not separate.

Also, the mp_allowmonsters CVar does not exist on all mods. Excluding Half-Life, the vanilla Counter-Strike does have that cvar (I do not know it's behaviour), but it's ReGameDLL implementation does not, and TFC does not have that CVar at all.

**Comment by QuakerLife** [comment]
Then what is the use of them right now in cs 1.6, for rick90 I clearly think it was done differently. If I need all the monsters, but what would be just on some maps (part on one, the other part on another), I can't separate them, they will load the limit all at once. + these turns (monsters lose their target, shoot with their backs, turn for 1 minute, and can barely run)

**Comment by JulianR0** [comment]
I assume you are using dynamic spawning?

You can build separate config files for each map, let's say map1_monster.cfg and map2_monster.cfg. Replace map1 and map2 with the appropiate map names.

Put a dummy entry data for a monster in an inaccesible place (outside world or a place no player can get to). Doing so will precache those monsters in those maps.

Something like:

```
{
"origin" "0 0 0"
"classname" "monster_houndeye"
}
{
"origin" "0 0 0"
"classname" "monster_bullchicken"
}
```

You would make a copy of these entries for every monster you want to precache. For the second map you do the same, but with different monsters. You can then remove them from the monster_precache.cfg.

See `cfg/example_monster.cfg` [(Here)](https://github.com/JulianR0/monstermod-redo/blob/tier3/cfg/example_monster.cfg)

Also, I'm aware that the AI is very, VERY barebones. Rick90 reworked the AI, so they are an improvement I have yet to implement. It's definitively planned, I just to want to first finish adding the remaining monsters that are pending on my Tier 3 milestone before I start working with it. Opposing Force monsters are done, only the Sven Co-op monsters are missing.

Hell, the project itself is a stub and I'm surprised with myself that I even made it this far, alone and as a novice C++ programmer. Not having any source code for other things to work with makes it even harder.

**Comment by QuakerLife** [comment]
I noticed that with half-life, not all monsters were added. there are no such as (monster_leech, monster_gman, monster_ichthyosaur, monster_tentacle, monster_barnacle, monster_nihilanth, monster_cockroach). Do not forget.

**Comment by QuakerLife** [comment]
ReGameDLL generally crashes when the player interacts with monster_scientist

**Comment by QuakerLife** [comment]
How to work with this, I take map for tests with half-life c3a1. Create c3a1_monster.cfg-copy "info_node" and monster entity data. But in the end it doesn't load anything. (Here is the "{
"origin" "-2136 8 -96"
"classname" "info_node"
}
{
"origin" "-2028 104 -96"
"classname" "info_node"
}
{
"origin" "-1916 16 -96"
"classname" "info_node"
}
{
"origin" "-2024 -88 -96"
"classname" "info_node"
}
{
"origin" "-2184 8 -68"
"classname" "info_node"
}
{
"origin" "-144 -872 628"
"classname" "info_node"
}
{
"origin" "-328 -836 628"
"classname" "info_node"
}
{
"origin" "-484 -836 628"
"classname" "info_node"
}
{
"origin" "-463 -100 584"
"classname" "info_node"
}
{
"origin" "-408 -100 584"
"classname" "info_node"
}
{
"origin" "-879 -100 396"
"classname" "info_node"
}
{
"origin" "-932 -100 396"
"classname" "info_node"
}
{
"origin" "-140 -1076 628"
"classname" "info_node"
}
{
"origin" "-1684 -1180 392"
"angle" "90"
"classname" "monster_alien_grunt"
}
{
"origin" "-2492 -1504 196"
"angle" "45"
"classname" "monster_alien_grunt"
}
{
"origin" "-2310 644 388"
"classname" "monster_alien_slave"
} "

**Comment by JulianR0** [comment]
It is not the current goal to add every single monster to the plugin.

```
monster_leech
monster_cockroach
monster_gman
monster_rat
```
Why would you want those monsters? They literally do nothing but unnecessarily precache additional models and sounds.

`monster_nihilant`

This is a hardcoded monster that has been specifically designed to work on an specific map (Half-Life's final level).

`monster_tentacle`

The problem with this monster is that it requires the monsters AI to be aware of sounds, which currently do not have such capability. I will consider adding it on a later time, but I can't make any promises.

```
monster_barnacle
monster_ichthyosaur
```

I see these as very redundant monsters, but I might add them.

> ReGameDLL generally crashes when the player interacts with monster_scientist

How did it crash? I have a ReGameDLL dedicated server myself and it never crashed. I've even made a quick test right now with a scientist and I'm unable to replicate the crash.

By the way, ideally you will want to put this crash on a separare issue, to keep things organized.

I'm closing this issue for now.
