### ISSUE TITLE
Can't compile on Linux g++ 12.2

### ISSUE THREAD

**Issue by Nord1cWarr1or** [JulianR0/monstermod-redo#4]
Hello, I tried to compile your project on g++ version 12.2 and get a warning:
```
/usr/bin/ld: strooper.o: warning: relocation against `_Z14CreateClassPtrI7CMShockEPT_S2_' in read-only section `.text'
```
when I'm trying to run the plugin on server, I got this error:
```
L 02/12/2023 - 13:43:10: [META] ERROR: dll: Failed query plugin '<monster_mm_i386.so>'; Couldn't open file '/home/maks/LGSM/serverfiles/cstrike/addons/mosntermod/monster_mm_i386.so': /home/maks/LGSM/serverfiles/cstrike/addons/mosntermod/monster_mm_i386.so: undefined symbol: _ZTV10CMStukabat
L 02/12/2023 - 13:43:10: [META] ERROR: dll: Skipping plugin '<monster_mm_i386.so>'; couldn't query
L 02/12/2023 - 13:43:10: [META] ERROR: dll: Couldn't close plugin file 'monster_mm_i386.so': invalid handle
```
P.s. I'm a newbie in programming, so I can't solve this by myself

**Comment by JulianR0** [comment]
> strooper.o: warning: relocation against `_Z14CreateClassPtrI7CMShockEPT_S2_' in read-only section `.text'

That's... bizzare. I didn't modify the shock trooper code since I added it. Taking a blind guess here but it could be a compiler issue. The plugin is meant to be compiled using a very old g++ version, after all (4.8).

I'll try using the same g++ version as you and look for a fix.

Alas, I'm currently outside of home for a few days and won't be able to work on this. But I will look at it as soon as I return on Tuesday.

> undefined symbol: _ZTV10CMStukabat

Looks like I forgot the linux side of this while I was working on the plugin. Gave a bit too much priority to windows.

From what I can see, the Makefile needs to be updated. The new monsters need to be included there. If my memory serves me right, you need to add:

`hwgrunt.o`
`rgrunt.o`
`flyingmonster.o`
`stukabat.o`

To the Makefile. Just open the Makefile with a text editor, then at the end of the OBJ section add the entries I mentioned. Then recompile.

**Comment by Nord1cWarr1or** [comment]
@JulianR0 thanks for ur answer.
Yes, it probably refers to the compiler version.
> Alas, I'm currently outside of home for a few days and won't be able to work on this. But I will look at it as soon as I return on Tuesday.

Sure, I'ill wait as long as it takes.
>From what I can see, the Makefile needs to be updated. The new monsters need to be included there. If my memory serves me right, you need to add:
hwgrunt.o
rgrunt.o
flyingmonster.o
stukabat.o
To the Makefile. Just open the Makefile with a text editor, then at the end of the OBJ section add the entries I mentioned. Then recompile.

I tried to do it now, but the result is the same...

Also I tried to compile the master branch, and I get same warn but for other file: `/usr/bin/ld: islave.o: warning: relocation against _ZN8CMISlave7ArmBeamEi in read-only section .text`

**Comment by JulianR0** [comment]
I tried to take a look at this but I became unable to replicate the warning message that you've shown. Tried with both G++ versions 4.8 and 9.

Nevertheless, I've updated the makefile to include the missing monsters, and the linux binary is now fixed. Ran it on a plain CS dedicated linux server and the plugin managed to load all OK.

The current build instruccions are way outdated and confusing, and knowing that the next Tier 3 milestone is going to take a while I provided pre-release binaries for both windows/linux until I can make proper, easy compilation instruccions. Grab a "beta" T3 release [here.](https://github.com/JulianR0/monstermod-redo/releases/tag/tier-3-beta1)

**Comment by Nord1cWarr1or** [comment]
I tested the compilation with the latest changes, but unfortunately this again failed with the same errors.. My Linux distribution: Garuda Linux (based on Arch). And the compiler is version 12.2.
Thanks anyway.
I can now use the version from the pre-release. There are a few problems there, too, but I will describe them separately in other issues.

I also tried compiling on my laptop with zorin os installed (based on ubuntu 20.04) and the compilation was successful, the module works.

**Comment by Nord1cWarr1or** [comment]
I can use an older compiler to compile on my laptop.
However, if you, @JulianR0, have some free time, please fix the compilation using the newest compiler. Because I could not install an older compiler on my desktop and it is not convenient to use my laptop to compile all the time.

**Comment by Nord1cWarr1or** [comment]
@JulianR0 it seems that everything OK now. I can compile the code from "tier 4" branch with g++ 12.2. Thanks!
