### ISSUE TITLE
[Tier 4] Monsters not respawn

### ISSUE THREAD

**Issue by Nord1cWarr1or** [JulianR0/monstermod-redo#9]
I compiled the last code from the Tier 4 branch, ([last commit](https://github.com/JulianR0/monstermod-redo/commit/750b9166666c21843089a08ac19a0c9bf6f876e5)) and now when I kill monsters, they are not spawns.

Mod: CS 1.6, with ReHLDS, ReGameDLL.
Config:
```
{
"origin" "-629 2233 -71"
"delay" "3"
"angles" "0 0 0"
"classname" "monster_zombie"
}
{
"origin" "-1814 2399 133"
"delay" "3"
"angles" "0 0 0"
"classname" "monster_houndeye"
}
{
"origin" "-1238 2100 37"
"delay" "3"
"angles" "0 0 0"
"classname" "monster_alien_slave"
}
{
"origin" "-1515 1828 37"
"delay" "3"
"angles" "0 0 0"
"classname" "monster_human_assassin"
}
# {
# "origin" "-432 1384 -92"
# "delay" "3"
# "angles" "0 0 0"
# "classname" "monster_hwgrunt"
# }
{
"origin" "-1673 1133 69"
"delay" "3"
"angles" "0 0 0"
"classname" "monster_alien_grunt"
}
```
This never happened before when I used the code from Tier-3.

**Comment by JulianR0** [comment]
Aahhh, forgot to update the example file.

The addition of the new monstermaker entity means that monsters no longer respawn by default. If you need to add respawning monsters you must use the monstermaker entity. Change your config to this:

```
{
"origin" "-629 2233 -71"
"angles" "0 0 0"
"delay" "3"
"monstercount" "-1"
"m_imaxlivechildren" "1"
"monstertype" "monster_zombie"
"classname" "monstermaker"
}
{
"origin" "-1814 2399 133"
"delay" "3"
"monstercount" "-1"
"m_imaxlivechildren" "1"
"monstertype" "monster_houndeye"
"classname" "monstermaker"
}
{
"origin" "-1238 2100 37"
"angles" "0 0 0"
"delay" "3"
"monstercount" "-1"
"m_imaxlivechildren" "1"
"monstertype" "monster_alien_slave"
"classname" "monstermaker"
}
{
"origin" "-1515 1828 37"
"angles" "0 0 0"
"delay" "3"
"monstercount" "-1"
"m_imaxlivechildren" "1"
"monstertype" "monster_human_assassin"
"classname" "monstermaker"
}
{
"origin" "-1673 1133 69"
"angles" "0 0 0"
"delay" "3"
"monstercount" "-1"
"m_imaxlivechildren" "1"
"monstertype" "monster_alien_grunt"
"classname" "monstermaker"
}
```
`monstertype` is the monster that should spawn from this spawnpoint.
`monstercount` is how many monsters should (re)spawn from this point, -1 makes it infinite (like it was before).
`m_imaxlivechildren` is how many monsters can spawn simultanesously in this point, 1 to replicate old respawn behaviour.
`delay` is how long to wait between spawns.

**Comment by Nord1cWarr1or** [comment]
Oh, I get it. That's a great feature!
